name: Build S24UltraSpoofer apk

on:
  workflow_dispatch

jobs:
  pre_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'  # Only release on main branch
        with:
          files: |
            **/*.apk
          name: "S24USpoofer LSPosed App"
          tag_name: "s24uspoofer-${{ github.run_number }}"
          body: |
            Automated build of S24USpoofer LSPosed App
            Build number: ${{ github.run_number }}
            Commit: ${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
